----------------------------------- T-SQL QUERIES -----------------------------------

-- 1. TOP n (after SELECT)
SELECT TOP 1 '#1- TOP n (after SELECT)',* FROM
(
	SELECT	1 AS S_NO, 'ADARSH' AS STUDENT_NAME
	UNION ALL
	SELECT	2 AS S_NO, 'ARUL' AS STUDENT_NAME
) T;

-- 2. TRY_CAST
SELECT '#2- TRY_CAST',TRY_CAST( '10 D' AS INT ) AS SAMPLES;

-- 3. ISNULL
SELECT '#3- ISNULL',ISNULL( TRY_CAST('10 D' AS INT) ,-1) AS SAMPLES;

-- 4. []
SELECT '#4- []','10 D' AS [SAMPLE DAYS];

-- 5. ISDATE()
SELECT '#5- ISDATE()',ISDATE( '2021/02/29' ) AS SAMPLES;

-- 6. GETDATE() - DATETIME version
SELECT '#6- GETDATE() - DATETIME version',GETDATE() AS SAMPLES;

-- 7. GETDATE() - DATE version
SELECT '#7- GETDATE() - DATE version', CAST( GETDATE() AS DATE ) AS SAMPLES;

-- 8. FORMAT
SELECT '#8- FORMAT',FORMAT( GETDATE(),'yyyyMMdd' ) AS SAMPLES;

-- 9. EOMONTH()
SELECT '#9- EOMONTH()',EOMONTH( GETDATE() ) AS SAMPLES;

-- 10. DATEADD - DAY - 3 parameter
SELECT '#10- DATEADD - DAY - 3 parameter',GETDATE() AS TODAY, DATEADD( DAY,2,GETDATE() ) AS SAMPLES;

-- 11. DATEADD - MONTH - 3 parameter
SELECT '#11- DATEADD - MONTH - 3 parameter',GETDATE() AS TODAY, DATEADD( MONTH,2,GETDATE() ) AS SAMPLES;

